### PR TITLE
port to  0.10

### PR DESCRIPTION
**Pull request by leokaplan**
Hi, this is the beginning of a port to 0.10.0.
At this point it just doesn't crash.
Most of the effects does not work because the canvas and stencil API has been reworked. 
I changed the canvas and stencil calls in a very naive way and tried to comment all my concerns.

### CODE REVIEW

**Comment by tanema** [comment]
This is pretty good, I have one thing to note that you could look at as well. In the new api you have to set the stencil and then the stencil test (that is why there is no inverted stencil anymore) You have changed all the stencil calls but not set the stencil tests. You could try that to start to get it to work. I have also made notes in the util file of what should be done there. If it is true that you cannot draw a canvas to itself (I don't know why that should be a constraint) then an intermediate canvas should be created and drawn to, then draw it back to the original canvas.

**Comment by leokaplan** [comment]
I'll experiment with two canvas in the process function

**Comment by leokaplan** [comment]
Hello, 
I've updated the code to use two canvases.
Now it works but the y axis of the light mouse is weird.

**Comment by leokaplan** [comment]
Now everything is working!

**Comment by tanema** [comment]
Awesome, I will check it out and take a look this evening.

**Comment by tanema** [comment]
Awesome work @leokaplan I finished up changing over the examples to make them all functional and fixed up some last remaining api changes and now the library is good to go for 0.10.0 because of your work. cheers!

**Pull request merged**
