### PR TITLE
Reuse canvas

### PR DESCRIPTION
**Pull request by buckle2000**
#21

### CODE REVIEW

**Comment by giann** [comment]
Is normal that you don't give the temp canvas any dimension ?

**Comment by buckle2000** [comment]
Its dimension is the window size by default.

**Comment by giann** [comment]
But you dont't always want that. You should use the dimensions of the original canvas.

**Comment by punk0x29a** [comment]
`Error: libraries/lightworld/util.lua:44: bad argument #1 to 'draw' (Drawable expected, got nil)
stack traceback:
	[C]: in function 'draw'
	libraries/lightworld/util.lua:44: in function 'cb'
	libraries/lightworld/util.lua:66: in function 'drawto'
	libraries/lightworld/util.lua:23: in function 'drawCanvasToCanvas'
	libraries/lightworld/util.lua:17: in function 'process'
	libraries/lightworld/postshader.lua:103: in function 'drawBlur'
	libraries/lightworld/init.lua:181: in function 'drawShadows'
	libraries/lightworld/init.lua:100: in function 'cb'
	libraries/lightworld/util.lua:66: in function 'drawto'
	libraries/lightworld/init.lua:97: in function 'draw'`

**Pull request closed without merging**
